name: mrm
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  res_client: ^0.8.3
  yaml: ^3.1.1
  json_annotation: ^4.6.0
  args: ^2.3.1
  glog: ^1.1.0
  collection: ^1.16.0
  http: ^0.13.4

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.4
  build_runner: ^2.1.11
  json_serializable: ^6.3.1

# dependency_overrides:
#   yaml:
#     git: https://github.com/farcaller/yaml.git
